name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Jab bhi main branch me push hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Jahan index.html maujood hai

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
